name: Initial Docker Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push initial image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/tumblr-agent"
          echo "Building image: $IMAGE_NAME"
          
          docker build -f docker/Dockerfile -t "$IMAGE_NAME:setup" .
          docker push "$IMAGE_NAME:setup"
          
          echo "✅ Package created successfully!"
          echo "You can now use the main workflow." 